# SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
# SPDX-License-Identifier: MIT

FROM golang:1.25

RUN go install github.com/Happy2018new/nemc-tan-lobby-solver/core/webrtc/examples/pion-to-pion/offer@latest

CMD ["offer"]
