package protocol

const (
	ContainerAnvilInput                      = iota // 0: 铁砧输入槽
	ContainerAnvilMaterial                          // 1: 铁砧材料槽
	ContainerAnvilResultPreview                     // 2: 铁砧结果预览槽
	ContainerSmithingTableInput                     // 3: 锻造台输入槽
	ContainerSmithingTableMaterial                  // 4: 锻造台材料槽
	ContainerSmithingTableResultPreview             // 5: 锻造台结果预览槽
	ContainerArmor                                  // 6: 盔甲槽
	ContainerLevelEntity                            // 7: 等级实体容器
	ContainerBeaconPayment                          // 8: 信标支付槽
	ContainerBrewingStandInput                      // 9: 酿造台输入槽
	ContainerBrewingStandResult                     // 10: 酿造台结果槽
	ContainerBrewingStandFuel                       // 11: 酿造台燃料槽
	ContainerCombinedHotBarAndInventory             // 12: 合并的快捷栏和物品栏
	ContainerCraftingInput                          // 13: 合成输入槽
	ContainerCraftingOutputPreview                  // 14: 合成输出预览槽
	ContainerRecipeConstruction                     // 15: 建筑类配方槽
	ContainerRecipeNature                           // 16: 自然类配方槽
	ContainerRecipeItems                            // 17: 物品类配方槽
	ContainerRecipeSearch                           // 18: 配方搜索槽
	ContainerRecipeSearchBar                        // 19: 配方搜索栏
	ContainerRecipeEquipment                        // 20: 装备类配方槽
	ContainerRecipeBook                             // 21: 配方书
	ContainerEnchantingInput                        // 22: 附魔台输入槽
	ContainerEnchantingMaterial                     // 23: 附魔台材料槽
	ContainerFurnaceFuel                            // 24: 熔炉燃料槽
	ContainerFurnaceIngredient                      // 25: 熔炉原料槽
	ContainerFurnaceResult                          // 26: 熔炉结果槽
	ContainerHorseEquip                             // 27: 马匹装备槽
	ContainerHotBar                                 // 28: 快捷栏
	ContainerInventory                              // 29: 物品栏
	ContainerShulkerBox                             // 30: 潜影盒
	ContainerTradeIngredientOne                     // 31: 交易材料一
	ContainerTradeIngredientTwo                     // 32: 交易材料二
	ContainerTradeResultPreview                     // 33: 交易结果预览槽
	ContainerOffhand                                // 34: 副手槽
	ContainerCompoundCreatorInput                   // 35: 化合物制造机输入槽
	ContainerCompoundCreatorOutputPreview           // 36: 化合物制造机输出预览槽
	ContainerElementConstructorOutputPreview        // 37: 元素构造器输出预览槽
	ContainerMaterialReducerInput                   // 38: 材料还原机输入槽
	ContainerMaterialReducerOutput                  // 39: 材料还原机输出槽
	ContainerLabTableInput                          // 40: 实验台输入槽
	ContainerLoomInput                              // 41: 织布机输入槽
	ContainerLoomDye                                // 42: 织布机染料槽
	ContainerLoomMaterial                           // 43: 织布机材料槽
	ContainerLoomResultPreview                      // 44: 织布机结果预览槽
	ContainerBlastFurnaceIngredient                 // 45: 高炉原料槽
	ContainerSmokerIngredient                       // 46: 烟熏炉原料槽
	ContainerTradeTwoIngredientOne                  // 47: 第二交易材料一
	ContainerTradeTwoIngredientTwo                  // 48: 第二交易材料二
	ContainerTradeTwoResultPreview                  // 49: 第二交易结果预览槽
	ContainerGrindstoneInput                        // 50: 砂轮输入槽
	ContainerGrindstoneAdditional                   // 51: 砂轮附加槽
	ContainerGrindstoneResultPreview                // 52: 砂轮结果预览槽
	ContainerStonecutterInput                       // 53: 切石机输入槽
	ContainerStonecutterResultPreview               // 54: 切石机结果预览槽
	ContainerCartographyInput                       // 55: 制图台输入槽
	ContainerCartographyAdditional                  // 56: 制图台附加槽
	ContainerCartographyResultPreview               // 57: 制图台结果预览槽
	ContainerBarrel                                 // 58: 木桶
	ContainerCursor                                 // 59: 光标
	ContainerCreatedOutput                          // 60: 已创建输出
	ContainerSmithingTableTemplate                  // 61: 锻造台模板槽
	ContainerCrafterLevelEntity                     // 62: 工匠等级实体
)

const (
	ContainerTypeInventory          = iota - 1 // -1: 物品栏类型
	ContainerTypeContainer                     // 0: 容器类型
	ContainerTypeWorkbench                     // 1: 工作台类型
	ContainerTypeFurnace                       // 2: 熔炉类型
	ContainerTypeEnchantment                   // 3: 附魔台类型
	ContainerTypeBrewingStand                  // 4: 酿造台类型
	ContainerTypeAnvil                         // 5: 铁砧类型
	ContainerTypeDispenser                     // 6: 发射器类型
	ContainerTypeDropper                       // 7: 投掷器类型
	ContainerTypeHopper                        // 8: 漏斗类型
	ContainerTypeCauldron                      // 9: 炼药锅类型
	ContainerTypeCartChest                     // 10: 箱子矿车类型
	ContainerTypeCartHopper                    // 11: 漏斗矿车类型
	ContainerTypeHorse                         // 12: 马匹类型
	ContainerTypeBeacon                        // 13: 信标类型
	ContainerTypeStructureEditor               // 14: 结构编辑器类型
	ContainerTypeTrade                         // 15: 交易类型
	ContainerTypeCommandBlock                  // 16: 命令方块类型
	ContainerTypeJukebox                       // 17: 唱片机类型
	ContainerTypeArmour                        // 18: 盔甲类型
	ContainerTypeHand                          // 19: 手持类型
	ContainerTypeCompoundCreator               // 20: 化合物制造机类型
	ContainerTypeElementConstructor            // 21: 元素构造器类型
	ContainerTypeMaterialReducer               // 22: 材料还原机类型
	ContainerTypeLabTable                      // 23: 实验台类型
	ContainerTypeLoom                          // 24: 织布机类型
	ContainerTypeLectern                       // 25: 讲台类型
	ContainerTypeGrindstone                    // 26: 砂轮类型
	ContainerTypeBlastFurnace                  // 27: 高炉类型
	ContainerTypeSmoker                        // 28: 烟熏炉类型
	ContainerTypeStonecutter                   // 29: 切石机类型
	ContainerTypeCartography                   // 30: 制图台类型
	ContainerTypeHUD                           // 31: HUD类型
	ContainerTypeJigsawEditor                  // 32: 拼图编辑器类型
	ContainerTypeSmithingTable                 // 33: 锻造台类型
	ContainerTypeChestBoat                     // 34: 箱子船类型
	ContainerTypeDecoratedPot                  // 35: 装饰罐类型
	ContainerTypeCrafter                       // 36: 工匠类型
)
