package packet

const (
	IDLogin                             = iota + 1   // 1: 客户端登录请求
	IDPlayStatus                                     // 2: 登录状态响应（成功/失败）
	IDServerToClientHandshake                        // 3: 服务器向客户端发送加密握手
	IDClientToServerHandshake                        // 4: 客户端响应加密握手
	IDDisconnect                                     // 5: 断开连接通知
	IDResourcePacksInfo                              // 6: 服务器资源包信息
	IDResourcePackStack                              // 7: 资源包加载顺序
	IDResourcePackClientResponse                     // 8: 客户端资源包加载响应
	IDText                                           // 9: 聊天消息/系统文本
	IDSetTime                                        // 10: 同步游戏时间
	IDStartGame                                      // 11: 初始化游戏数据
	IDAddPlayer                                      // 12: 添加玩家实体
	IDAddActor                                       // 13: 添加其他实体（生物等）
	IDRemoveActor                                    // 14: 移除实体
	IDAddItemActor                                   // 15: 添加掉落物实体
	_                                                // 16: （跳过）
	IDTakeItemActor                                  // 17: 实体拾取物品
	IDMoveActorAbsolute                              // 18: 实体绝对坐标移动
	IDMovePlayer                                     // 19: 玩家移动
	IDPassengerJump                                  // 20: 坐骑跳跃
	IDUpdateBlock                                    // 21: 更新单个方块
	IDAddPainting                                    // 22: 添加画实体
	IDTickSync                                       // 23: 世界刻同步
	_                                                // 24: （跳过）
	IDLevelEvent                                     // 25: 世界事件（音效/粒子等）
	IDBlockEvent                                     // 26: 方块事件（箱子开关等）
	IDActorEvent                                     // 27: 实体事件（受伤/死亡等）
	IDMobEffect                                      // 28: 实体药水效果
	IDUpdateAttributes                               // 29: 更新实体属性
	IDInventoryTransaction                           // 30: 物品栏操作事务
	IDMobEquipment                                   // 31: 更新实体装备
	IDMobArmourEquipment                             // 32: 更新实体护甲
	IDInteract                                       // 33: 实体交互
	IDBlockPickRequest                               // 34: 方块拾取请求
	IDActorPickRequest                               // 35: 实体拾取请求
	IDPlayerAction                                   // 36: 玩家动作（挖掘/放置等）
	_                                                // 37: （跳过）
	IDHurtArmour                                     // 38: 护甲损坏
	IDSetActorData                                   // 39: 更新实体数据
	IDSetActorMotion                                 // 40: 设置实体运动速度
	IDSetActorLink                                   // 41: 设置实体关联（骑乘等）
	IDSetHealth                                      // 42: 设置生命值
	IDSetSpawnPosition                               // 43: 设置重生点
	IDAnimate                                        // 44: 实体动画
	IDRespawn                                        // 45: 玩家重生
	IDContainerOpen                                  // 46: 打开容器
	IDContainerClose                                 // 47: 关闭容器
	IDPlayerHotBar                                   // 48: 设置快捷栏
	IDInventoryContent                               // 49: 同步容器内容
	IDInventorySlot                                  // 50: 更新单个容器格子
	IDContainerSetData                               // 51: 容器数据更新（熔炉进度等）
	IDCraftingData                                   // 52: 同步合成配方
	_                                                // 53: （跳过）
	IDGUIDataPickItem                                // 54: GUI物品选择
	IDAdventureSettings                              // 55: 冒险模式设置
	IDBlockActorData                                 // 56: 方块实体数据更新
	IDPlayerInput                                    // 57: 玩家输入（移动/跳跃）
	IDLevelChunk                                     // 58: 区块数据发送
	IDSetCommandsEnabled                             // 59: 启用/禁用命令
	IDSetDifficulty                                  // 60: 设置游戏难度
	IDChangeDimension                                // 61: 切换维度
	IDSetPlayerGameType                              // 62: 设置玩家游戏模式
	IDPlayerList                                     // 63: 玩家列表更新
	IDSimpleEvent                                    // 64: 简单事件通知
	IDEvent                                          // 65: 通用事件
	IDSpawnExperienceOrb                             // 66: 生成经验球
	IDClientBoundMapItemData                         // 67: 地图数据
	IDMapInfoRequest                                 // 68: 地图信息请求
	IDRequestChunkRadius                             // 69: 请求区块加载半径
	IDChunkRadiusUpdated                             // 70: 区块半径更新确认
	_                                                // 71: （跳过）
	IDGameRulesChanged                               // 72: 游戏规则更新
	IDCamera                                         // 73: 设置摄像机视角
	IDBossEvent                                      // 74: BOSS血条事件
	IDShowCredits                                    // 75: 播放结束字幕
	IDAvailableCommands                              // 76: 同步可用命令
	IDCommandRequest                                 // 77: 执行命令请求
	IDCommandBlockUpdate                             // 78: 命令方块更新
	IDCommandOutput                                  // 79: 命令执行反馈
	IDUpdateTrade                                    // 80: 更新村民交易
	IDUpdateEquip                                    // 81: 更新装备（已弃用）
	IDResourcePackDataInfo                           // 82: 资源包分块信息
	IDResourcePackChunkData                          // 83: 资源包分块数据
	IDResourcePackChunkRequest                       // 84: 请求资源包分块
	IDTransfer                                       // 85: 跨服务器传送
	IDPlaySound                                      // 86: 播放音效
	IDStopSound                                      // 87: 停止音效
	IDSetTitle                                       // 88: 设置标题（标题/副标题等）
	IDAddBehaviourTree                               // 89: 添加行为树（教育版）
	IDStructureBlockUpdate                           // 90: 结构方块更新
	IDShowStoreOffer                                 // 91: 显示商店商品
	IDPurchaseReceipt                                // 92: 购买凭证
	IDPlayerSkin                                     // 93: 玩家皮肤更新
	IDSubClientLogin                                 // 94: 子客户端登录
	IDAutomationClientConnect                        // 95: 自动化客户端连接
	IDSetLastHurtBy                                  // 96: 设置最后攻击者
	IDBookEdit                                       // 97: 编辑书内容
	IDNPCRequest                                     // 98: NPC交互请求
	IDPhotoTransfer                                  // 99: 照片传输
	IDModalFormRequest                               // 100: 发送表单给客户端
	IDModalFormResponse                              // 101: 客户端表单响应
	IDServerSettingsRequest                          // 102: 请求服务器设置
	IDServerSettingsResponse                         // 103: 服务器设置响应
	IDShowProfile                                    // 104: 显示玩家资料
	IDSetDefaultGameType                             // 105: 设置默认游戏模式
	IDRemoveObjective                                // 106: 移除记分板目标
	IDSetDisplayObjective                            // 107: 设置记分板显示位置
	IDSetScore                                       // 108: 更新记分板分数
	IDLabTable                                       // 109: 实验台操作
	IDUpdateBlockSynced                              // 110: 同步方块更新
	IDMoveActorDelta                                 // 111: 实体相对移动
	IDSetScoreboardIdentity                          // 112: 设置记分板实体关联
	IDSetLocalPlayerAsInitialised                    // 113: 标记本地玩家初始化完成
	IDUpdateSoftEnum                                 // 114: 更新命令枚举选项
	IDNetworkStackLatency                            // 115: 网络延迟测试
	_                                                // 116: （跳过）
	IDScriptCustomEvent                              // 117: 脚本自定义事件
	IDSpawnParticleEffect                            // 118: 生成粒子效果
	IDAvailableActorIdentifiers                      // 119: 同步可用实体标识符
	_                                                // 120: （跳过）
	IDNetworkChunkPublisherUpdate                    // 121: 更新区块发布范围
	IDBiomeDefinitionList                            // 122: 生物群系定义列表
	IDLevelSoundEvent                                // 123: 播放层级音效
	IDLevelEventGeneric                              // 124: 通用层级事件
	IDLecternUpdate                                  // 125: 讲台更新
	_                                                // 126: （跳过）
	_                                                // 127: （跳过）
	_                                                // 128: （跳过）
	IDClientCacheStatus                              // 129: 客户端缓存状态
	IDOnScreenTextureAnimation                       // 130: 屏幕材质动画
	IDMapCreateLockedCopy                            // 131: 创建锁定地图副本
	IDStructureTemplateDataRequest                   // 132: 请求结构模板数据
	IDStructureTemplateDataResponse                  // 133: 结构模板数据响应
	_                                                // 134: （跳过）
	IDClientCacheBlobStatus                          // 135: 客户端缓存块状态
	IDClientCacheMissResponse                        // 136: 客户端缓存缺失响应
	IDEducationSettings                              // 137: 教育版设置
	IDEmote                                          // 138: 玩家表情动作
	IDMultiPlayerSettings                            // 139: 多人游戏设置
	IDSettingsCommand                                // 140: 设置命令
	IDAnvilDamage                                    // 141: 铁砧损坏
	IDCompletedUsingItem                             // 142: 物品使用完成
	IDNetworkSettings                                // 143: 网络设置
	IDPlayerAuthInput                                // 144: 玩家认证输入
	IDCreativeContent                                // 145: 同步创造模式物品栏
	IDPlayerEnchantOptions                           // 146: 玩家附魔选项
	IDItemStackRequest                               // 147: 物品堆请求（交易/合成）
	IDItemStackResponse                              // 148: 物品堆请求响应
	IDPlayerArmourDamage                             // 149: 玩家护甲损伤
	IDCodeBuilder                                    // 150: 代码构建器功能
	IDUpdatePlayerGameType                           // 151: 更新玩家游戏模式
	IDEmoteList                                      // 152: 可用表情列表
	IDPositionTrackingDBServerBroadcast              // 153: 位置跟踪数据库广播
	IDPositionTrackingDBClientRequest                // 154: 位置跟踪数据库请求
	IDDebugInfo                                      // 155: 调试信息
	IDPacketViolationWarning                         // 156: 协议违规警告
	IDMotionPredictionHints                          // 157: 移动预测提示
	IDAnimateEntity                                  // 158: 实体动画序列
	IDCameraShake                                    // 159: 摄像机震动效果
	IDPlayerFog                                      // 160: 玩家迷雾设置
	IDCorrectPlayerMovePrediction                    // 161: 修正玩家移动预测
	IDItemComponent                                  // 162: 物品组件
	IDFilterText                                     // 163: 文本过滤
	IDClientBoundDebugRenderer                       // 164: 客户端调试渲染
	IDSyncActorProperty                              // 165: 同步实体属性
	IDAddVolumeEntity                                // 166: 添加体积实体
	IDRemoveVolumeEntity                             // 167: 移除体积实体
	IDSimulationType                                 // 168: 设置模拟类型
	IDNPCDialogue                                    // 169: NPC对话
	IDEducationResourceURI                           // 170: 教育版资源URI
	IDCreatePhoto                                    // 171: 创建照片
	IDUpdateSubChunkBlocks                           // 172: 更新子区块方块
	IDPhotoInfoRequest                               // 173: 照片信息请求
	IDSubChunk                                       // 174: 子区块数据
	IDSubChunkRequest                                // 175: 请求子区块
	IDClientStartItemCooldown                        // 176: 客户端物品冷却
	IDScriptMessage                                  // 177: 脚本消息
	IDCodeBuilderSource                              // 178: 代码构建器源码
	IDTickingAreasLoadStatus                         // 179: 常加载区域状态
	IDDimensionData                                  // 180: 维度数据
	IDAgentAction                                    // 181: 教育版代理动作
	IDChangeMobProperty                              // 182: 更改生物属性
	IDLessonProgress                                 // 183: 课程进度
	IDRequestAbility                                 // 184: 请求能力启用
	IDRequestPermissions                             // 185: 请求权限
	IDToastRequest                                   // 186: 显示Toast提示
	IDUpdateAbilities                                // 187: 更新玩家能力
	IDUpdateAdventureSettings                        // 188: 更新冒险设置
	IDDeathInfo                                      // 189: 死亡信息
	IDEditorNetwork                                  // 190: 编辑器网络
	IDFeatureRegistry                                // 191: 特性注册表
	IDServerStats                                    // 192: 服务器统计
	IDRequestNetworkSettings                         // 193: 请求网络设置
	IDGameTestRequest                                // 194: 游戏测试请求
	IDGameTestResults                                // 195: 游戏测试结果
	IDUpdateClientInputLocks                         // 196: 更新客户端输入锁定
	IDClientCheatAbility                             // 197: 客户端作弊能力
	IDCameraPresets                                  // 198: 摄像机预设
	IDUnlockedRecipes                                // 199: 解锁配方
	IDCameraInstruction                 = iota + 101 // 200: 摄像机指令
	IDCompressedBiomeDefinitionList                  // 201: 压缩生物群系定义
	IDTrimData                                       // 202: 盔甲纹饰数据
	IDOpenSign                                       // 203: 打开告示牌编辑
	IDAgentAnimation                                 // 204: 代理动画（教育版）
	IDRefreshEntitlements                            // 205: 刷新用户权限
	IDPlayerToggleCrafterSlotRequest                 // 206: 切换合成槽位
	IDSetPlayerInventoryOptions                      // 207: 设置玩家物品栏选项
	IDSetHud                                         // 208: 设置HUD元素
	IDAwardAchievement                               // 209: 授予成就
	IDClientBoundCloseForm                           // 210: 强制关闭表单
)
